### ISSUE TITLE
Templated messages

### ISSUE THREAD

**Issue by mschmidt-healthx** [graylog-labs/graylog-plugin-slack#10]
It would be awesome if the slack callback supported templates for the message content like the email callback does, so users could build their own message however they want.

**Comment by lucas-bremond** [comment]
+1

Thanks for this amazing plug-in. Templating would indeed be awesome.

**Comment by HrothgarWrecker** [comment]
+1

**Comment by ken5scal** [comment]
👍

**Comment by dbinoj** [comment]
:+1:

**Comment by SotirisBK** [comment]
+1

**Comment by Aenima4six2** [comment]
I'll take this.

**Comment by Aenima4six2** [comment]
PR out -> https://github.com/graylog-labs/graylog-plugin-slack/pull/50
