### ISSUE TITLE
Add context to alerts with custom fields

### ISSUE THREAD

**Issue by patcable** [graylog-labs/graylog-plugin-slack#35]
I'm looking to add a "See More" link to alerts that fire with custom fields, since that way I could quickly get to the extra information. I'm doing this because the extra information in this case is a stack trace, and makes for a huge message into Slack, but also from a usability standpoint it makes it a bit easier for a dev to click and see what triggered an alert.

Java isn't my first programming language, and by far not my best -- but from what I can tell: I think it'd be possible to do this if the `value` var at https://github.com/Graylog2/graylog-plugin-slack/blob/master/src/main/java/org/graylog2/plugins/slack/callback/SlackAlarmCallback.java#L79-L95 was modified to append a "(See More Info)" link if the user has specified a graylog2 server URL that points to `graylogUri + "messages/" + index + "/" + id`. 

This assumes that the return of `result.getMatchingMessages()` returns something similar to the `matching_messages` array referenced in the [HTTP alert callback docs](http://docs.graylog.org/en/2.1/pages/streams/alerts.html#http-alert-callback). I imagine it does, but totally guessing.

Thoughts? Help?

**Comment by Aenima4six2** [comment]
@patcable There is a PR out now to add a link to the current message. The goal will be to create a first class template property (link) that you can add to the messages. Let me know if this is what you are looking for.
