### ISSUE TITLE
"Notify Channel" problem and custom fields

### ISSUE THREAD

**Issue by nhproject** [graylog-labs/graylog-plugin-slack#45]
Hi,

I installed the new plugin version (2.4.0), I work with the newest Graylog version as well.

1. I'm creating many alerts and use the Slack as my alerts callback, but I noticed that when I check the "Notify Channel" option, then the  alert sent does not contain the bold title ("*Alert for Graylog stream STREAM*") and the condition's description underneath. When this option is not checked - it does show up. 

2. How do I use the "custom fields" field?

Thanks,

Nitzan

**Comment by SotirisBK** [comment]
I hope I am not hijacking, but I have a relevant issue.
I tried also to add some of my fields to custom field but did not see them in message. 
It would be ideal if I could have the permalink as well in the message

**Comment by Aenima4six2** [comment]
Please try using custom fields with the new template message feature and report back. If the problem persists, I'll personally look into the issue.
