### ISSUE TITLE
Plugin is loaded but it doesn show in Configuration page.

### ISSUE THREAD

**Issue by Minkiu** [graylog-labs/graylog-plugin-slack#46]
Hello,

it's the exact same problem that in this thread: https://github.com/graylog-labs/graylog-plugin-threatintel/issues/1

But with the Slack plugin,  I installed the 2.4.0 (https://github.com/graylog-labs/graylog-plugin-slack/releases/download/2.4.0/graylog-plugin-slack-2.4.0.jar) through wget into the plugin folder,

it is recognized and loaded, yet I can't configure it.

`2017-05-16_11:38:08.54709 2017-05-16 11:38:08,545 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Slack 2.4.0 [org.graylog2.plugins.slack.callback.SlackAlarmCallback]`

Any advice?

I am also running Graylog 2.1.1+01d50e5.

**Comment by joschi** [comment]
@Minkiu This plugin doesn't provide any system configuration (available on the *System* / *Configurations* page).

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by davidmaitland** [comment]
@joschi the problem with this is that readme isn't very clear on how to use this plugin in the first place. Especially as someone who is new Greylog (which was super easy to get setup and working), but it 5x as long to figure out how to use this plugin after it was installed, having to look through logs to check it was even being loaded by Greylog and then finding issues like this.

The [usage](https://github.com/graylog-labs/graylog-plugin-slack#usage) section in the readme only has one step for Slack. As someone who hasn't used Mattermost, I looked over step two thinking it was something to do with Mattermost. Maybe someone who understands Greylog / this plugin can update the readme?

So for anyone else who comes across this issue, you can configure this plugin as an output under `/system/outputs`.

But saying all that thanks for the work on this plugin, it's just what I needed.
