### ISSUE TITLE
Messages on Slack just show Backlog items (x) but (no message) as the content.

### ISSUE THREAD

**Issue by kowsari** [graylog-labs/graylog-plugin-slack#47]
Hi
Thanks for this useful plugin. However I have a problem in that when errors are generated I see a message on slack that shows x number of backlog items but doesnt show the actual messages. It shows them as (no message). 
I realize that this might be a misconfiguration in alert configruration or notification options, but any help is appreciated.

Thanks

**Comment by derFunk** [comment]
Same for me - I don't see the log entry which caused the alert, only the previous X lines are shown in Slack.
