### ISSUE TITLE
Stream output color definition not working

### ISSUE THREAD

**Issue by jskrns** [graylog-labs/graylog-plugin-slack#48]
Changed the default but has no effect in Slack

**Comment by jskrns** [comment]
Ignore, seems to be working now!

**Comment by bronius** [comment]
Did the color just start working for you out of the blue?  Also, is the custom color applied when you send a dummy message by clicking Test?  (Color is not working for me in either live messages or dummy Test messages)

**Comment by jskrns** [comment]
Yes, out of the blue. I wish I could remember more but don't recall doing anything differently. I'm not sure how to do Test messages so can't speak to that.
