### ISSUE TITLE
URLs are not URL-encoded breaking the markdown rendering in Mattermost

### ISSUE THREAD

**Issue by svnk** [graylog-labs/graylog-plugin-slack#54]
We use the plugin in mattermost and have messages like this:

<pre>
*New message in Graylog stream [Foo Exceptions]
(https://graylog/streams/58311e2b2ab79c080136c1d9/messages?q=*&rangetype=relative&relative=3600)*:
</pre>

the star (*) in q=* is seen as ending the italic section leaving the message rendered as 

*New message in Graylog stream [Foo Exceptions](https://graylog/streams/58311e2b2ab79c080136c1d9/messages?q=* &rangetype=relative&relative=3600)*:

(w/o the blank. the github markdown renderer is smarter than the markdown renderer of mattermost.)

If the URL is URL-encoded, this can be avoided.

**Comment by Aenima4six2** [comment]
I'll take a look at this.

**Comment by towolf** [comment]
Actually, with https://github.com/graylog-labs/graylog-plugin-slack/pull/60 in, the asterisk should be gone.

Not that this means, that this Issue is not relevant. But the newest build should work around it.

**Comment by towolf** [comment]
Ah, scratch that, there are two links in the message, and the second one is still broken.

**Comment by towolf** [comment]
Please merge PR #63 @Aenima4six2, tested here successfully
