### ISSUE TITLE
Is this support for graylog 2.3?

### ISSUE THREAD

**Issue by kieulam141** [graylog-labs/graylog-plugin-slack#55]
Hi guys,
I recently updated our graylog cluster to version 2.3.But when I install this plugin and restart graylog server, It failed because of this unsupported plugin.
Is there any update for this version?

**Comment by Aenima4six2** [comment]
I forked the plugin and added templated logging messages. It works with 2.3. Ill post up shortly.

**Comment by kieulam141** [comment]
Thanks Aenima4six2 !

**Comment by kieulam141** [comment]
Hi Aenima4six2, have you post up?

**Comment by Aenima4six2** [comment]
yep, https://github.com/Aenima4six2/graylog-plugin-slack-fork

**Comment by Aenima4six2** [comment]
@kieulam141 I'm taking over this repo and merged all my changes up. Let me know if your issue still exists.

**Comment by kieulam141** [comment]
Hi Aenima4six2,
It works.Thank u very much.
