### ISSUE TITLE
Context help in Alert Configuration UI under Custom Message box references old documentation

### ISSUE THREAD

**Issue by bronius** [graylog-labs/graylog-plugin-slack#62]
When configuring a new or editing existing Alert Configuration, the help text under the Custom Message refers to an older (1.3) version of Graylog but should refer to 2.3 (and under a different section in docs at that). See:
![graylog alert link to docs](https://user-images.githubusercontent.com/2348390/33400557-1e95ec66-d51c-11e7-93cb-5d9049a55155.jpg)

In:
https://github.com/graylog-labs/graylog-plugin-slack/blob/bd1cc8061cdf80b301c5283d16abed1772b96b11/src/main/java/org/graylog2/plugins/slack/configuration/SlackConfigurationRequestFactory.java#L52
the URL:
```http://docs.graylog.org/en/1.3/pages/streams.html```
should probably be:
```http://docs.graylog.org/en/2.3/pages/streams/alerts.html#email-alert-notification```
or maybe without the named anchor if that's likely to change.

**Comment by Aenima4six2** [comment]
Good catch. All fixed in 3.0.1
