### ISSUE TITLE
How to enable "Short mode"?

### ISSUE THREAD

**Issue by rolfwessels** [graylog-labs/graylog-plugin-slack#70]
From the code it seems that the configuration should have a boolean option to enable short mode but I can't seem to find it.

Could you please add some documentation about adding short mode?

Thanks

**Comment by Aenima4six2** [comment]
Short mode is only available for [outputs](http://docs.graylog.org/en/2.4/pages/streams.html#outputs).

**Comment by rolfwessels** [comment]
Thanks.

For anyone who wants only a very minimal backlog. The following template will do that 
```${if backlog}
${foreach backlog message}
${message.message}
${end}...
${else}<No backlog>
${end}```
