### ISSUE TITLE
Field "Custom message" not worked

### ISSUE THREAD

**Issue by BrainsRage** [graylog-labs/graylog-plugin-slack#71]
Hi, we have a problem. 
With your plugin v2.4 we has beautiful messages like 
![image](https://user-images.githubusercontent.com/7159616/36536657-9899e68c-17ef-11e8-9f9a-1134879a4bcf.png)
But when we upgrade version to 3.0.1 message began to look so
![image](https://user-images.githubusercontent.com/7159616/36536759-e67a5a3a-17ef-11e8-92b8-83a920e9430f.png)
We tryed to change "custom message" field in plugin options, but no difference.
Help us to use v3. Thx.

**Comment by Aenima4six2** [comment]
@BrainsRage, we need more information to help diagnose your issue. Please include the following:

1. Graylog Version
1. Notification configuration (including your custom message)

**Comment by BrainsRage** [comment]
1. Graylog 2.4.3+2c41897
2. 
![image](https://user-images.githubusercontent.com/7159616/36558934-707ed786-182e-11e8-8296-88b841367dc6.png)
```
##########
Alert Description: ${check_result.resultDescription}
Date: ${check_result.triggeredAt}
Stream ID: ${stream.id}
Stream title: ${stream.title}
Stream description: ${stream.description}
Alert Condition Title: ${alert_condition.title}
${if stream_url}Stream URL: ${stream_url}${end}

Triggered condition: ${check_result.triggeredCondition}
##########

${if backlog}Last messages accounting for this alert:
${foreach backlog message}${message}

${end}${else}<No backlog>
${end}

```

**Comment by Aenima4six2** [comment]
@BrainsRage , can you send a test message from Graylog and report back what shows up in your slack channel please?

**Comment by BrainsRage** [comment]
Yes.
![image](https://user-images.githubusercontent.com/7159616/36656997-8f2821e0-1aec-11e8-8c0b-65a37bb67bcc.png)

**Comment by derFunk** [comment]
Same issue here. The `custom_message` field for *Outputs* is not used. It's used for *Alerts* though.
- `Graylog 2.4.3+2c41897`
- `graylog-plugin-slack-3.0.1.jar`

**Comment by SonicGD** [comment]
Hi, any news on this? We have the same problem

**Comment by Aenima4six2** [comment]
@SonicGD I'm cutting a branch for this as we speak.

**Comment by Aenima4six2** [comment]
Issue fixed in 3.1.0.

**Comment by andela-sjames** [comment]
@Aenima4six2 can't find the `.jar` file for the new release?

**Comment by Aenima4six2** [comment]
@andela-sjames Looks like Travis had an issue pushing the jar. I'm re-running CI/CD for this release.

Fixed -> [Release](https://github.com/graylog-labs/graylog-plugin-slack/releases/download/3.1.0/graylog-plugin-slack-3.1.0.jar)

**Comment by BrainsRage** [comment]
Fixed, thanks!

**Comment by andela-sjames** [comment]
Thanks
